# https://github.com/developmentseed/how/issues/149
# ssh-keygen -m pem -t rsa -b 4096 -C developmentseed/project-seed-styled -f deploy_key

# YAML anchors for base definitions
base_def: &base_def
  docker:
    - image: node:12
  working_directory: ~/repo
  environment:
    - DEVELOPMENT_BRANCH: develop
    - PRODUCTION_BRANCH: master

restore_cache_def: &restore_cache_def
  # Download and cache dependencies
  keys:
  - v1-dependencies-{{ checksum "package.json" }}
  - v1-dependencies-  # fallback if checksum fails

##
## START Circle CI configuration
##

version: 2.1
jobs:
  prepare:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - app/assets/scripts/config/local.js
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn lint
      - run: yarn lint:css
  test:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn gulp collecticons
      - run: yarn test
  ci:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - cypress-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - cypress-deps-{{ .Branch }}-
            - cypress-deps-
      - run: yarn install
      - save_cache:
          key: cypress-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: yarn cy:test
  deploy-surge-dev:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - run:
          name: Building staging site
          command: yarn stage
      - run:
          name: Deploy to surge
          command: |
            cp ./dist/index.html ./dist/200.html
            ./node_modules/surge/lib/cli.js --project ./dist --domain https://rezoning-dev.surge.sh

  build-production:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - run:
          name: Building production site
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy-production:
    docker:
      - image: 'circleci/python:3.9'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Sync files at S3
          command: aws s3 sync --delete /tmp/workspace/dist s3://${PRODUCTION_S3_BUCKET}/

workflows:
  version: 2
  main:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      # - deploy-surge-dev:
      #     requires:
      #       - lint
      #       - test
      #       - prepare
      #     filters:
      #       branches:
      #         only: develop
      - build-production:
          requires:
            - lint
            - test
            - prepare
          filters:
            branches:
              only:
                - master
      - deploy-production:
          requires:
            - lint
            - test
            - prepare
            - build-production
          filters:
            branches:
              only:
                - master
